set_property IOSTANDARD LVCMOS33 [get_ports {LED_STATE[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_STATE[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_STATE[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_STATE[0]}]
set_property PACKAGE_PIN K17 [get_ports clk]
set_property PACKAGE_PIN M19 [get_ports rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports SCL]
set_property IOSTANDARD LVCMOS33 [get_ports SDA]
set_property PACKAGE_PIN F20 [get_ports SDA]
set_property PACKAGE_PIN F19 [get_ports SCL]
set_property PACKAGE_PIN T12 [get_ports {LED_STATE[3]}]
set_property PACKAGE_PIN U12 [get_ports {LED_STATE[2]}]
set_property PACKAGE_PIN V12 [get_ports {LED_STATE[1]}]
set_property PACKAGE_PIN W13 [get_ports {LED_STATE[0]}]

